name: Build Next.js web application
on: 
  push:
    branches:
      - main
      - '!refs/tags/*'  # Exclude tag pushes to prevent re-triggering
  workflow_dispatch:
jobs:
  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
    - name: Download site content
      uses: actions/download-artifact@v4
      with:
        name: static-site
    - name: View content of artifact
      run: ls -R
    - name: Archive site content
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'site.zip'
    - name: Create GitHub Release
      id: create_new_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: build-${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_new_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./site.zip
        asset_name: site-v${{ github.run_number }}.zip
        asset_content_type: application/zip  
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install NPM dependencies
      run: npm install
    - name: Build project assets
      run: npm run build
    - name: Upload static sit site content
      uses: actions/upload-artifact@v4
      with: 
        name: static-site
        path: .next/